In [1]:
import pandas as pd
a = pd.read_csv('kc_housing_distances.csv')
b = pd.read_csv('zipcodedata.csv')
c = pd.read_csv('walkability_scores.csv')

c['id']=a['id']
df1 = a.merge(b, on='zipcode', how='outer')
df = df1.merge(c, on='id', how='outer')


df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,minimum_distance_to_metro,population,land,population_density,units,units_occupied,med_value,med_income,calc_pd,walk_score
0,7129300520,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0.0,0.0,...,1.302968,24092,4.85,4966,9290,8668,283100.0,58707.0,4967.422680,39
1,4060000240,2014-06-23,205425.0,2,1.00,880,6780,1.0,0.0,0.0,...,2.089548,24092,4.85,4966,9290,8668,283100.0,58707.0,4967.422680,62
2,4058801670,2014-07-17,445000.0,3,2.25,2100,8201,1.0,0.0,2.0,...,1.894527,24092,4.85,4966,9290,8668,283100.0,58707.0,4967.422680,23
3,2976800796,2014-09-25,236000.0,3,1.00,1300,5898,1.0,0.0,0.0,...,1.643102,24092,4.85,4966,9290,8668,283100.0,58707.0,4967.422680,29
4,6874200960,2015-02-27,170000.0,2,1.00,860,5265,1.0,0.0,0.0,...,1.264256,24092,4.85,4966,9290,8668,283100.0,58707.0,4967.422680,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21415,2525049086,2014-03-10,2720000.0,4,3.25,3990,18115,2.0,0.0,0.0,...,4.137484,2971,1.44,2059,1163,1062,1000001.0,183833.0,2063.194444,50
21416,2525049113,2014-07-25,1950000.0,4,3.50,4065,18713,2.0,0.0,0.0,...,3.703551,2971,1.44,2059,1163,1062,1000001.0,183833.0,2063.194444,65
21417,3262300485,2015-04-21,2250000.0,5,5.25,3410,8118,2.0,0.0,0.0,...,3.462462,2971,1.44,2059,1163,1062,1000001.0,183833.0,2063.194444,23
21418,6447300365,2014-11-13,2900000.0,5,4.00,5190,14600,2.0,0.0,1.0,...,4.118677,2971,1.44,2059,1163,1062,1000001.0,183833.0,2063.194444,7
21419,3262300818,2015-02-27,1870000.0,4,3.75,3790,8797,2.0,0.0,0.0,...,3.324468,2971,1.44,2059,1163,1062,1000001.0,183833.0,2063.194444,22

In [2]:
df.to_csv('DataTable.csv', index=False)